version: '2'

services:
  develop-php:
    extends: develop-base
    build: ./develop-php

  develop-haskell:
    extends: develop-base
    build: ./develop-haskell

  develop-dotnet:
    extends: develop-base
    build: ./develop-dotnet

  develop-base:
    build: ./develop-base
    volumes:
      - ~/.dotfiles:/home/user/.dotfiles
      - ~/.ssh:/home/user/.ssh
